import torch
import torch.nn as nn
import torch.nn.functional as F


class FPN(nn.Module):
    """Feature Pyramid Network (FPN) neck.

    Builds a multi-scale feature pyramid from backbone outputs.

    Args:
        in_channels (list[int]): Input channel sizes for each backbone stage.
        out_channels (int): Output channel size for all pyramid levels.
        num_outs (int): Number of output pyramid levels. When num_outs >
            len(in_channels), extra levels are added via strided convolution.
    """

    def __init__(self, in_channels, out_channels, num_outs):
        super(FPN, self).__init__()
        assert len(in_channels) >= 1

        self.in_channels = in_channels
        self.out_channels = out_channels
        self.num_outs = num_outs

        self.lateral_convs = nn.ModuleList()
        self.fpn_convs = nn.ModuleList()

        for in_ch in in_channels:
            self.lateral_convs.append(
                nn.Conv2d(in_ch, out_channels, kernel_size=1)
            )
            self.fpn_convs.append(
                nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1)
            )

        # Extra levels (P6, P7, …) generated by strided 3x3 conv applied on
        # the last FPN output level (not the raw backbone feature)
        self.extra_convs = nn.ModuleList()
        for i in range(num_outs - len(in_channels)):
            in_ch = out_channels
            self.extra_convs.append(
                nn.Conv2d(in_ch, out_channels, kernel_size=3, stride=2, padding=1)
            )

    def forward(self, inputs):
        """
        Args:
            inputs (tuple[Tensor]): Feature maps from backbone, ordered from
                smallest stride to largest stride (C2 … C5).

        Returns:
            tuple[Tensor]: Multi-scale feature maps (P2 … P6/P7).
        """
        assert len(inputs) == len(self.in_channels)

        # Build lateral feature maps
        laterals = [
            lateral_conv(inputs[i])
            for i, lateral_conv in enumerate(self.lateral_convs)
        ]

        # Top-down path: add upsampled coarser features
        for i in range(len(laterals) - 1, 0, -1):
            laterals[i - 1] = laterals[i - 1] + F.interpolate(
                laterals[i], size=laterals[i - 1].shape[-2:], mode='nearest'
            )

        # Apply 3x3 convs to get final feature maps
        outs = [
            self.fpn_convs[i](laterals[i]) for i in range(len(laterals))
        ]

        # Append extra levels (applied on the last FPN output, not raw backbone)
        if self.extra_convs:
            extra_source = outs[-1]
            for extra_conv in self.extra_convs:
                extra_source = F.relu(extra_conv(extra_source))
                outs.append(extra_source)

        return tuple(outs)
